---

version: '3'

services:

  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  gif_bot:
    container_name: gif_bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file: '.env'
    depends_on:
      - db
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

networks:
  backend:

